build documentation after publish to npm

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -1,32 +1,31 @@
 name: Generate Documentation
 
 on:
-  push:
-    branches:
-      - master
-    paths:
-      - 'src/**'
+  workflow_run:
+    workflows: ['Publish to NPM']
+    branches: [master]
+    types:
+      - completed
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-      with:
-        token: ${{ secrets.ACCESS_TOKEN }}
-    - name: Set up Node.js
-      uses: actions/setup-node@v1
-      with:
-        node-version: 16
-    - name: Install dependencies
-      run: yarn install
-    - name: Generate Documentation
-      run: npx typedoc
-    - name: Commit and Push Documentation
-      run: |
-        git config --global user.name ${{ secrets.GIT_USER_NAME }}
-        git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
-        git add docs
-        git commit -m "Update documentation" || true  # The '|| true' is to avoid failure in case there are no changes
-        git push
-    
+      - uses: actions/checkout@v2
+        with:
+          token: ${{ secrets.ACCESS_TOKEN }}
+      - name: Set up Node.js
+        uses: actions/setup-node@v1
+        with:
+          node-version: 16
+      - name: Install dependencies
+        run: yarn install
+      - name: Generate Documentation
+        run: npx typedoc
+      - name: Commit and Push Documentation
+        run: |
+          git config --global user.name ${{ secrets.GIT_USER_NAME }}
+          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
+          git add docs
+          git commit -m "Update documentation" || true  # The '|| true' is to avoid failure in case there are no changes
+          git push
